import { AUTH_PREFIX_PATH } from '@/constants/route.constant'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import { ADMIN, USER } from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const authNavigationConfig: NavigationTree[] = [
    {
        key: 'authentication',
        path: '',
        title: 'احراز هویت',
        translateKey: 'nav.authentication.authentication',
        icon: 'authentication',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        meta: {
            horizontalMenu: {
                layout: 'default',
            },
        },
        subMenu: [
            {
                key: 'authentication.signIn',
                path: '',
                title: 'ورود',
                translateKey: 'nav.authentication.signIn',
                icon: 'signIn',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'authentication.signInSimple',
                        path: `${AUTH_PREFIX_PATH}/sign-in-simple`,
                        title: 'ساده',
                        translateKey: 'nav.authentication.signInSimple',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'authentication.signInSide',
                        path: `${AUTH_PREFIX_PATH}/sign-in-side`,
                        title: 'کناری',
                        translateKey: 'nav.authentication.signInSide',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'authentication.signInSplit',
                        path: `${AUTH_PREFIX_PATH}/sign-in-split`,
                        title: 'تقسیم',
                        translateKey: 'nav.authentication.signInSplit',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'authentication.signUp',
                path: '',
                title: 'ثبت‌نام',
                translateKey: 'nav.authentication.signUp',
                icon: 'signUp',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'authentication.signUpSimple',
                        path: `${AUTH_PREFIX_PATH}/sign-up-simple`,
                        title: 'ساده',
                        translateKey: 'nav.authentication.signUpSimple',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'authentication.signUpSide',
                        path: `${AUTH_PREFIX_PATH}/sign-up-side`,
                        title: 'کناری',
                        translateKey: 'nav.authentication.signUpSide',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'authentication.signUpSplit',
                        path: `${AUTH_PREFIX_PATH}/sign-up-split`,
                        title: 'تقسیم',
                        translateKey: 'nav.authentication.signUpSplit',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'authentication.forgotPassword',
                path: '',
                title: 'فراموشی رمز عبور',
                translateKey: 'nav.authentication.forgotPassword',
                icon: 'forgotPassword',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'authentication.forgotPasswordSimple',
                        path: `${AUTH_PREFIX_PATH}/forgot-password-simple`,
                        title: 'ساده',
                        translateKey: 'nav.authentication.forgotPasswordSimple',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'authentication.forgotPasswordSide',
                        path: `${AUTH_PREFIX_PATH}/forgot-password-side`,
                        title: 'کناری',
                        translateKey: 'nav.authentication.forgotPasswordSide',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'authentication.forgotPasswordSplit',
                        path: `${AUTH_PREFIX_PATH}/forgot-password-split`,
                        title: 'تقسیم',
                        translateKey: 'nav.authentication.forgotPasswordSplit',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'authentication.resetPassword',
                path: '',
                title: 'بازنشانی رمز عبور',
                translateKey: 'nav.authentication.resetPassword',
                icon: 'resetPassword',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'authentication.resetPasswordSimple',
                        path: `${AUTH_PREFIX_PATH}/reset-password-simple`,
                        title: 'ساده',
                        translateKey: 'nav.authentication.resetPasswordSimple',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'authentication.resetPasswordSide',
                        path: `${AUTH_PREFIX_PATH}/reset-password-side`,
                        title: 'کناری',
                        translateKey: 'nav.authentication.resetPasswordSide',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'authentication.resetPasswordSplit',
                        path: `${AUTH_PREFIX_PATH}/reset-password-split`,
                        title: 'تقسیم',
                        translateKey: 'nav.authentication.resetPasswordSplit',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
        ],
    },
]


export default authNavigationConfig
